apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: devops-challenge
spec:
  selector:
    app: devops-challenge
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
